
spring:
  # 为你的应用起个名字，该名字将注册到eureka注册中心
  application:
    name: config-client
    
  #dev, test, prod
  profiles:
    active: test
    
  #App.java package    
  main:
    sources: com.xmh
    
server:
  port: 2004
  
  # bind to a specific NIC
  #address:
  
  # session timeout in minutes
  #session-timeout:
  
  #the context path, defaults to '/', eg http://localhost:2001/eureka-client/
  servlet:
    context-path: /config-client
  
  # the servlet path, defaults to '/'
  #servlet-path:
